openapi: 3.0.3

info:
  title: FoodOrder API
  version: 1.0.0
  description: API documentation for FoodOrder backend.

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  $ref: "./paths/index.yaml"

  
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      $ref: "./schemas/user.yaml"

    Restaurant:
      $ref: "./schemas/restaurant.yaml"

    Cart: 
      $ref: "./schemas/cart.yaml#/Cart"
    CartItem: 
      $ref: "./schemas/cart.yaml#/CartItem"
    CartItemOption:
      $ref: "./schemas/cart.yaml#/CartItemOption"

    OrderOption: 
      $ref: "./schemas/order.yaml#/OrderOption"
    OrderItem:
      $ref: "./schemas/order.yaml#/OrderItem"
    OrderDeliveryAddress:
      $ref: "./schemas/order.yaml#/OrderDeliveryAddress"
    Order: 
      $ref: "./schemas/order.yaml#/Order"

    Payment:
      $ref: "./schemas/payment.yaml"

    MenuItem:
      $ref: "./schemas/menuItem.yaml#/MenuItem"
    OptionGroup:
      $ref: "./schemas/menuItem.yaml#/OptionGroup"
    Option:
      $ref: "./schemas/menuItem.yaml#/Option"
    CreateMenuItemInput:
      $ref: "./schemas/menuItem.yaml#/CreateMenuItemInput"
    UpdateMenuItemInput:
      $ref: "./schemas/menuItem.yaml#/UpdateMenuItemInput"

 
  responses:
    LoginSuccess:
      $ref: "./responses/auth.yaml#/LoginSuccess"
    LoginInvalid:
      $ref: "./responses/auth.yaml#/LoginInvalid"
    RefreshSuccess:
      $ref: "./responses/auth.yaml#/RefreshSuccess"
    LogoutSuccess:
      $ref: "./responses/auth.yaml#/LogoutSuccess"
    VerificationEmailSuccess:
      $ref: "./responses/auth.yaml#/VerificationEmailSuccess"
    VerifyEmailSuccess:
      $ref: "./responses/auth.yaml#/VerifyEmailSuccess"
    PasswordResetRequestSuccess:
      $ref: "./responses/auth.yaml#/PasswordResetRequestSuccess"
    PasswordResetSuccess:
      $ref: "./responses/auth.yaml#/PasswordResetSuccess"
    OauthUrlSuccess:
      $ref: "./responses/auth.yaml#/OauthUrlSuccess"
    OauthLoginSuccess:
      $ref: "./responses/auth.yaml#/OauthLoginSuccess"
    CompleteProfileSuccess:
      $ref: "./responses/auth.yaml#/CompleteProfileSuccess"
